### ISSUE TITLE
SDK not exposing the raw meta data properly from the response

### ISSUE THREAD

**Issue by tansanDOTeth** [alchemyplatform/alchemy-sdk-js#104]
In the response when you query with `withMetadata: true`, it returns the contract symbol and the contract name.

For example,
```javascript
[
     {
...
      "contractMetadata": {
        "name": "Genuine Undead",
        "symbol": "GU",
        "totalSupply": "8",
        "tokenType": "ERC721"
      }
...
}
]
```

In the data structure returned by the SDK, all the names or titles include the token ID. I only want the contract name and/or symbol. 

For example,

```javascript
rawMetadata: {
  attributes: (4) [{…}, {…}, {…}, {…}],
  date: 1654355106928,
  description: "RISE AND SHINE",
  dna: "52de95bd3f07d9130621fa51d30e70fb9e831e35",
  edition: 156,
  image: "ipfs://QmVUgP9fnFh9R6HF3eMP3ro2fxvv76fQsrBud7yyPDAMdQ/156.png",
  name: "GENUINE UNDEAD #156",
}
```

I am looking for just the string `Genuine Undead`

**Comment by thebrianchen** [comment]
@tansanDOTeth which SDK method are you using? If you only want the metadata for the contract, you can call `getContractMetadata()`, which only returns the name of the contract. You can see the docs for this method [here](https://github.com/alchemyplatform/alchemy-sdk-js/blob/main/docs-md/classes/NftNamespace.md#getcontractmetadata).

**Comment by tansanDOTeth** [comment]
> @tansanDOTeth which SDK method are you using? If you only want the metadata for the contract, you can call `getContractMetadata()`, which only returns the name of the contract. You can see the docs for this method [here](https://github.com/alchemyplatform/alchemy-sdk-js/blob/main/docs-md/classes/NftNamespace.md#getcontractmetadata).

My apologies for leaving out the most important details. I was using `getNftsForOwner`.

**Comment by thebrianchen** [comment]
@tansanDOTeth the backend just started including the contract metadata in the response not too long ago. We should have a PR out for this soon.

**Comment by tansanDOTeth** [comment]
> @tansanDOTeth the backend just started including the contract metadata in the response not too long ago. We should have a PR out for this soon.

Ah I see! Looking forward to it!
