### ISSUE TITLE
why can't use alchemy_filteredNewFullPendingTransactions?

### ISSUE THREAD

**Issue by gd-cho** [alchemyplatform/alchemy-sdk-js#106]
I need to monitor the transaction information of `to` and `from` field at the specified address.
but I use `alchemy.ws.on({method: "alchemy_filteredNewFullPendingTransactions", address: '0x...'})` is monitor full pending transaction.

And I use `alchemy.ws.on({method: "alchemy_pendingTransactions"})`, it just can monitor to or from field address....

**Comment by thebrianchen** [comment]
@gd-cho 

The only accepted `method` property in the SDK is `alchemy_pendingTransactions`. You can specify the same to and from address to get the same behavior as `alchemy_filteredNewFullPendingTransactions`. I'll have a PR out for the error checking shortly.
