### ISSUE TITLE
getNftsForOwner() pageSize not working for RINKEBY network.

### ISSUE THREAD

**Issue by cwalternicolas** [alchemyplatform/alchemy-sdk-js#108]
Calling the method getNftsForOwner() with a pageSize different from "100" (default) is not working for RINKEBY but it works fine on MAINNET.

I cannot find any warning in the documentation about this limitation, it is a bug?

Steps to reproduce:

1. Instantiate the SDK with the RINKEBY network:

```javascript
const alchemy = new Alchemy({
    apiKey: 'your api key'
    network: Network.ETH_RINKEBY
});
```

2. Call the getNftsForOwner method with pageSize different from 100. The "walletAddress" of the example has 117 NFTs:

```javascript
const nfts =  await alchemy.nft.getNftsForOwner(walletAddress, { pageSize: 50 });
```

The response of the code above is returning 100 NFTs.

**Comment by thebrianchen** [comment]
@cwalternicolas Thanks for flagging this! I was able to reproduce the issue, and this seems like an issue with our backends. I'll check with the team and keep this thread updated.

**Comment by ayang-rkjs** [comment]
@cwalternicolas Thanks for filing this issue! As you alluded to, we don't support this parameter on Rinkeby. I will update our docs to reflect this. We're not planning to add this functionality on Rinkeby, as the Rinkeby testnet is being deprecated after the Merge in favor of Goerli.

**Comment by thebrianchen** [comment]
Marking the issue as closed since it's WAI.
