### ISSUE TITLE
FR: Support Moonbase

### ISSUE THREAD

**Issue by sai1024** [alchemyplatform/alchemy-sdk-js#109]
hi, the SDK currently supports the following chains
* Ethereum: Mainnet, Goerli
* Polygon: Mainnet, Mumbai
* Optimism: Mainnet, Goerli, Kovan
* Arbitrum: Mainnet, Goerli, Rinkeby
* Astar: Mainnet

I want to support moonbase chain as well😂

**Comment by thebrianchen** [comment]
@sai1024 Thanks for filing an issue! Please also open a feature request in our [roadmap](https://roadmap.alchemy.com/b/feature-requests/) as well. The chains we prioritize are based on customer demand, so I'll leave this thread open for now.

**Comment by thebrianchen** [comment]
Marking the issue as closed due to inactivity.
