### ISSUE TITLE
Typescript error 'erc20' missed 

### ISSUE THREAD

**Issue by octavioamu** [alchemyplatform/alchemy-sdk-js#117]
https://github.com/alchemyplatform/alchemy-sdk-js/blob/ac866cd070d3e6682a56d346a064a4e7d4c0ad59/src/api/core-namespace.ts#L398
Seems there is are missed parameters here as should be string[] | 'erc20' | 'DEFAULT_TOKENS'

**Comment by thebrianchen** [comment]
@octavioamu Thanks for pointing this out! This is covered in #124 and should be published in the next release
