### ISSUE TITLE
Throws when NFT description is an object

### ISSUE THREAD

**Issue by alexvobo** [alchemyplatform/alchemy-sdk-js#118]
https://github.com/alchemyplatform/alchemy-sdk-js/blob/519f0c2e9900a064f0cb23f70f75a1c07a6bdd0f/src/util/util.ts#L95

This throws a type error when the description is an object because `.join(' ')` can only be called on an array.

Specifically, when I'm trying to call `.getNftsForOwner(address)` and there's an NFT where `description`:`{...}`

One NFT will prevent the rest from fetching.

**Comment by thebrianchen** [comment]
@alexvobo Thanks for flagging this. The description field should always be a string. Do you have the owner or contract address for me to repro? Thanks!

**Comment by thebrianchen** [comment]
@alexvobo Thanks for the issue and PR! I made a quick PR in #126 since your PR will also incorrectly stringify the description if the field is `string[]` type. This should be fixed in the next release!
