### ISSUE TITLE
Support AIRDROPS in NftExcludeFilters

### ISSUE THREAD

**Issue by rbruels** [alchemyplatform/alchemy-sdk-js#136]
There seems to be an implementation of an `AIRDROPS` filter according to the `getNfts` documentation:

https://docs.alchemy.com/reference/sdk-getnfts

But currently the SDK only supports `SPAM`. It'd be great to have an airdrop filter in the SDK, especially since some airdrops are not marked correctly as spam.

**Comment by thebrianchen** [comment]
The PR for that has been merged and should be out in the next release!

**Comment by rbruels** [comment]
> The PR for that has been merged and should be out in the next release!

👏 Awesome!

**Comment by thebrianchen** [comment]
Marking this issue as closed, but feel free to ask any other questions here. Keep an eye out for `v2.1.1`!
