### ISSUE TITLE
FR: Support multiple `excludeFilters` in `getNftsForOwner()`

### ISSUE THREAD

**Issue by rbruels** [alchemyplatform/alchemy-sdk-js#145]
I'm not sure of the conditions required to detect an airdrop, but using the 2.1.1 SDK with the `NftExcludeFilters.AIRDROPS` exclude filter doesn't seem to filter out airdropped NFTs.

Using this code:

```
alchemy.nft.getNftsForOwner(address, {
   excludeFilters: [NftExcludeFilters.SPAM, NftExcludeFilters.AIRDROPS],
});
```

I am still seeing airdropped NFTs in the returned list.

**Comment by thebrianchen** [comment]
@rbruels Can you please share an example request with the owner address?

**Comment by rbruels** [comment]
@thebrianchen You bet. 

```
alchemy.nft.getNftsForOwner('0x4db95b98706c56bb8cf1476018ee4ce9d2811bbf', {
   excludeFilters: [NftExcludeFilters.SPAM, NftExcludeFilters.AIRDROPS],
});
```

Airdropped NFTs include:
- Top DlArt Ticket #2
- Simple FL Official #5
- Gyaku Rebels Official #4
- Cool NFTLottery Origin #3
- APE Uniswap V3 Positions Origin #2

**Comment by thebrianchen** [comment]
@rbruels The NFT API currently does not support multiple `excludeFilters` at the moment, and the endpoint will simply process the first enum you pass in. Support for multiple filters is on our backlog at the moment, but we can revisit if there's enough developer demand.

I'll leave this issue open meanwhile, and update it if anything changes!

**Comment by rbruels** [comment]
@thebrianchen I notice just specifying `AIRDROPS` doesn't filter out these airdropped NFTs either. 

```
alchemy.nft.getNftsForOwner('0x4db95b98706c56bb8cf1476018ee4ce9d2811bbf', {
   excludeFilters: [NftExcludeFilters.AIRDROPS],
});
```

still returns the airdropped NFTs I listed above. Thoughts?

Worth noting there are quite a few docs and interfaces that do say that multiple filters can be applied (and the type of `excludeFilters` is an array, which implies multiple entries are supported)... see: 
- https://github.com/alchemyplatform/alchemy-sdk-js/blob/7342bef7d443739247555a65f630ff2746f13f79/docs-md/interfaces/GetBaseNftsForOwnerOptions.md
- https://docs.alchemy.com/reference/getnfts
- https://github.com/alchemyplatform/alchemy-sdk-js/blob/53be393/src/types/types.ts#L560

**Comment by thebrianchen** [comment]
I just checked with the NFT API team, and we're currently catching up on our airdrop ingestion, which is why you're seeing some false positives. It should be caught up soon though.

And yes, we'll need to update the docs to reflect that only one filter is supported. The roadmap includes supporting multiple exclude filters, which is why the SDK is typed this way to avoid a breaking change in the future. Sorry for the inconvenience!

**Comment by thebrianchen** [comment]
@rbruels Multiple exclude filters should now work with the `getNftsForOwner()` endpoint! Marking this issue as closed since it's fixed but feel free to ask anything other questions you may have!
