### ISSUE TITLE
Is the API keys are considered a secret?

### ISSUE THREAD

**Issue by OrDuan** [alchemyplatform/alchemy-sdk-js#146]
Hi!

Should API keys keep in secret? 
What could an attacker do if he has my API key?

Thanks

**Comment by thebrianchen** [comment]
@OrDuan Thanks for writing in! The main way we recommend users protect their API keys is by using Alchemy allowlisting functionalities. If you click on your app from the Alchemy Dashboard, you will be taken tot he App main page where you will see a button on the top right that says "Security".

By clicking that button, you will see a popup that lets you add allowlisted IPs and allowlisted domains. Once you add those, only the IPs that you allow will be able to send requests to your Alchemy API Key.

Marking this issue as closed, but feel free to ask any other questions you may have!
