### ISSUE TITLE
FR: Add effective fee (or fee data) to getAssetTransfers

### ISSUE THREAD

**Issue by xdzurman** [alchemyplatform/alchemy-sdk-js#156]
Hello.

**Is your feature request related to a problem? Please describe.**
(effective) Fee data is vital for any serious implementation of transaction history. Is there any chance it could be added to the `alchemy_getAssetTransfers` method? 

Otherwise, for each transaction, `getTransactionReceipt` has to be called, which basically re-fetches already known data with the addition of fees and would massively bloat necessary request count.

**Describe the solution you'd like**
Along with other fields, effective fee amount would be returned.

Thanks

**Comment by thebrianchen** [comment]
@xdzurman Since the the transaction receipt payload is quite large, it'd take a nontrivial amount of eng work to support. We'll look into making batch requests on top of the existing payload.

**Comment by thebrianchen** [comment]
Updating with blocked ticket on #159.
