### ISSUE TITLE
getContractMetadata API vs SDK

### ISSUE THREAD

**Issue by jadbox** [alchemyplatform/alchemy-sdk-js#162]
### [REQUIRED] Environment

- Browser version: Chrome 106
- Alchemy SDK version: 2.2.0

### [REQUIRED] Describe the problem

The getContractMetadata API returns useful openSea data that the SDK does not currently include.

**Comment by thebrianchen** [comment]
Thanks for bringing this up @jadbox. Should have something out in the coming couple weeks.

**Comment by thebrianchen** [comment]
This is being worked on in #164.
