### ISSUE TITLE
Error: invalid object key - maxFeePerGas (argument="transaction:maxFeePerGas"

### ISSUE THREAD

**Issue by shenzhimeng** [alchemyplatform/alchemy-sdk-js#173]
### [REQUIRED] Environment

- Browser version:
- Alchemy SDK version:2.2.0

### [REQUIRED] Describe the problem
https://docs.alchemy.com/docs/how-to-send-transactions-on-ethereum
<img width="556" alt="image" src="https://user-images.githubusercontent.com/7116717/200113261-a6f73c33-3609-4efe-bb19-9fee142c8437.png">

error info：
<img width="612" alt="image" src="https://user-images.githubusercontent.com/7116717/200113292-e4ba1aad-3536-4189-a243-3e9f6fcbd52c.png">
i found it
<img width="507" alt="image" src="https://user-images.githubusercontent.com/7116717/200113325-7095cf34-51f9-4cc2-9604-e833febd37fe.png">
WTF

**Comment by shenzhimeng** [comment]
i forgot to write the type

**Comment by whales-chen** [comment]
服了 我也是这个问题，咋解决的
