### ISSUE TITLE
Axios request incorrectly sets Accept-Encoding header when browser is detected

### ISSUE THREAD

**Issue by daviddzhang** [alchemyplatform/alchemy-sdk-js#174]
### [REQUIRED] Environment

- Browser version: Chrome Version 107.0.5304.87
- Alchemy SDK version: 2.2.0

### [REQUIRED] Describe the problem
When `alchemy.nft.getNftsForOwnerIterator(...)` is called, the request fails with `Refused to set unsafe header "Accept-Encoding"`. 
#### How to reproduce:
Call any function that uses `sendAxiosRequest`.
#### Relevant code or sample repro:
[This commit flips the boolean logic of whether to include this header in requests](https://github.com/alchemyplatform/alchemy-sdk-js/commit/0009f349a60fed4d8e693d9aff2d629a067d2c75#diff-fa9c0d9d8fd185d46d0635c59710ad0ca4476f32c0efe5f606be01307fbf14feR24). I don't even think reproducing this is worth your time, you can just look at the change and see that it's incorrect.

**Comment by thebrianchen** [comment]
@daviddzhang Thanks for flagging this! Will have a fix for this out shortly.
