### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getWebSocketProvider')

### ISSUE THREAD

**Issue by shenzhimeng** [alchemyplatform/alchemy-sdk-js#175]
<img width="673" alt="image" src="https://user-images.githubusercontent.com/7116717/200169776-77b48466-d415-4a40-a804-b23c1f4d35e9.png">
error info:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/7116717/200169884-065c48ff-fb3a-44f9-9b64-8ee739333508.png">

**Comment by thebrianchen** [comment]
@shenzhimeng Which version of the SDK are you using? `getWebSocketProvider()` wasn't exported until `v2.2.0`.
