### ISSUE TITLE
Breaks Jest tests

### ISSUE THREAD

**Issue by elie222** [alchemyplatform/alchemy-sdk-js#197]
### [REQUIRED] Environment

- Browser version: no browser
- Alchemy SDK version: 2.2.1

### [REQUIRED] Describe the problem

Alchemy SDK breaks our Jest tests:

```
    Details:

    /home/runner/work/..../node_modules/alchemy-sdk/dist/esm/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as utils from './api/utils';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

#### How to reproduce:

Use the SDK with Jest.

**Comment by thebrianchen** [comment]
@elie222 Thanks for filing the bug report! We'll get to debugging this in the coming weeks.

**Comment by dphilipson** [comment]
Hi @elie222 , I am looking into this. I would be interested in more information about your setup. A minimal example for me runs successfully.

To attempt to repro, I ran
```
mkdir repro
cd repro
npm init --yes
npm add alchemy-sdk jest
mkdir tests
echo 'it("imports alchemy-sdk", () => console.log(require("alchemy-sdk")));' > tests/index.test.js
npx jest
```
Doing so successfully runs the Jest test, importing `alchemy-sdk` and logging its contents to console.

In particular, I would be interested in how you are starting your Jest tests, if you're using any preprocessors like Babel or TypeScript, and if you have any nondefault settings in your Jest config.

**Comment by elie222** [comment]
Ours is for a Next.js project with Jest.

Best,
Eliezer

**Comment by thebrianchen** [comment]
@elie222 Have you tried some of the steps from the discussion links on this [SO post](https://stackoverflow.com/questions/70916761/next-js-and-jest-syntaxerror-cannot-use-import-statement-outside-a-module?rq=1)? This seems more like an issue with how next.js and jest are importing the modules, since the Alchemy SDK exports `cjs`, `es`, and `esm` dists in the final build.
