### ISSUE TITLE
FR: Add support to subscribe to `newHeads` directly

### ISSUE THREAD

**Issue by andkom** [alchemyplatform/alchemy-sdk-js#203]
### Environment

- Browser version: Node v16.13
- Alchemy SDK version: 2.2.3

### Describe the problem

It's impossible to subscribe to `newHeads` websocket event via sdk methods. Subscription to `block` event only returns block number.

#### How to reproduce:

Method 1:

```javascript
alchemy.ws.on('newHeads', (data) => {
   console.log(data);
});

// result:
unhandled: Event {
  tag: 'newheads',
  listener: [Function (anonymous)],
  once: false,
  _lastBlockNumber: -2,
  _inflight: false
}

no further events
```

Method 2:

```javascript
alchemy.ws.on({ method: 'newHeads' }, (data) => {
   console.log(data);
});

// Unhandled rejection Error: Invalid method name newHeads. Accepted method names: alchemy_pendingTransactions,alchemy_minedTransactions

```

**Comment by luisgerardodev** [comment]
You must use 'block' as the event name when using the SDK, like this:

```ts
alchemy.ws.on('block', (blockNumber: number) => {
  console.log(blockNumber)
})
```

**Comment by andkom** [comment]
@luisgerardodev yes, but i want receive full header object. Alchemy WS API supports it.

**Comment by andkom** [comment]
@thebrianchen thanks, I need it to receive base fee updates.
