### ISSUE TITLE
WebSocketNamespace constructor error

### ISSUE THREAD

**Issue by adacai1982** [alchemyplatform/alchemy-sdk-js#207]
### [REQUIRED] Environment

- Browser version:
- Alchemy SDK version: v2.2.3

### [REQUIRED] Describe the problem
WebSocketNamespace constructor failed to save config

#### How to reproduce:
create an instance of Alchemy and then try to listen to some alchemy event

**Comment by thebrianchen** [comment]
@adacai1982 Can you provide a more detailed repro? Which part of the config is the SDK failing to save? You should not be trying to instantiate the WebsocketNamespace directly.

**Comment by thebrianchen** [comment]
Closing due to the lack of activity.
