### ISSUE TITLE
method getNftMetadata doesn't return totalSupply for erc1155 token

### ISSUE THREAD

**Issue by Fsociety-sem** [alchemyplatform/alchemy-sdk-js#214]
### [REQUIRED] Environment

- Browser version:
- Alchemy SDK version: 2.2.4

### [REQUIRED] Describe the problem
method getNftMetadata doesn't return amount for erc1155 token. But if I call getNftsForOwner, it returns balance which is equals to amount. Tried different networks(polygon testnet, eth mainnet)
#### How to reproduce:
call the method with any multi token
#### Relevant code or sample repro:
```
await this.alchemySDK.nft.getNftMetadata(contractAddress, tokenId)
RES:
  contract: {
    address: '0xe08919ff2353da4168d1b338d89010f37ca11af2',
    name: undefined,
    symbol: undefined,
    totalSupply: undefined,
    tokenType: 'ERC1155'
  },
  tokenId: '6',
  tokenType: 'ERC1155',
  title: 'Susanoo',
  description: 'test descr',
  timeLastUpdated: '2022-12-15T16:34:14.026Z',
  metadataError: undefined,
  rawMetadata: {
    name: 'Susanoo',
    description: 'test descr',
    image: 'ipfs://QmdZusq12j7NyX1a8YpcCCs4E5PcVnwYdUaEgnS5eeAawR',
    attributes: []
  },
  tokenUri: {
    raw: 'ipfs://QmPA1GJY3rN9S1mmGqEmDDh4GPn49c5wcHsY7t1uF8gd59',
    gateway: 'https://alchemy.mypinata.cloud/ipfs/QmPA1GJY3rN9S1mmGqEmDDh4GPn49c5wcHsY7t1uF8gd59'
  },
  media: [
    {
      raw: 'ipfs://QmdZusq12j7NyX1a8YpcCCs4E5PcVnwYdUaEgnS5eeAawR',
      gateway: 'https://ipfs.io/ipfs/QmdZusq12j7NyX1a8YpcCCs4E5PcVnwYdUaEgnS5eeAawR'
    }
  ],
  spamInfo: undefined
}
```

**Comment by thebrianchen** [comment]
@Fsociety-sem We try to provide `totalSupply` on a best-effort basis, and it's currently only available for erc721 contracts. The contract in your example is an erc1155, and we currently don't support those. I'm going to mark this issue as closed but feel free to ask any other questions you may have!
