### ISSUE TITLE
Contract info not saturated for CryptoKitties

### ISSUE THREAD

**Issue by rbruels** [alchemyplatform/alchemy-sdk-js#221]
### Environment

Node.js with Alchemy SDK 2.2.4

### Problem

Calling `getNftMetadata()` on a Cryptokitty (`0x06012c8cf97BEaD5deAe237070F9587f8E7A266d`) returns no contract in the contract information. Example:

```
const { Alchemy } = require('alchemy-sdk');
const alchemy = new Alchemy({
  /* YOUR API KEY AND STUFF */
});
alchemy.nft.getNftMetadata(
  '0x06012c8cf97BEaD5deAe237070F9587f8E7A266d',
  '633961',
).then(response => {
  console.log(response);
}).catch(err => {
});
```

Result:

```
{
...<snip>...
  contract: {
    address: '0x06012c8cf97bead5deae237070f9587f8e7a266d',
    name: '',
    symbol: '',
    totalSupply: '',
    tokenType: 'ERC721'
  },
...<snip>...
}
```

[Etherscan seems to show the name correctly](https://etherscan.io/address/0x06012c8cf97bead5deae237070f9587f8e7a266d).

**Comment by rbruels** [comment]
Solid point. We'll work around it for now and will TODO on this being resolved. Thanks.

**Comment by thebrianchen** [comment]
@rbruels I was going through old issues and saw that cryptokitties is now ingested. Going to mark this as closed.
