### ISSUE TITLE
bug: alchemy-sdk getNftsForContract response don't give pageKey

### ISSUE THREAD

**Issue by ki502** [alchemyplatform/alchemy-sdk-js#234]
bug: alchemy-sdk getNftsForContract response don't give pageKey

"alchemy-sdk": "^2.2.5" not use pageKey

alchemy.nft
    .getNftsForContract(contractAddress, options)

no answer response pageKey

**Comment by thebrianchen** [comment]
@ki502 Thanks for catching and flagging this! This is an bug with the backend REST endpoint as well, and the backend team is working on a fix. I'll update this issue when it's fixed.

**Comment by thebrianchen** [comment]
@ki502 This issue has been fixed on the backend and should work now.
