### ISSUE TITLE
FR: Add exports for BigNumbers

### ISSUE THREAD

**Issue by Xirynx** [alchemyplatform/alchemy-sdk-js#265]
**Is your feature request related to a problem? Please describe.**
Currently, the library does not let you access the BigNumber utility methods provided by ethers. I find myself having to install the library separately in order to use its functionality, because I cannot find a way to use them directly from the alchemy-sdk.

**Describe the solution you'd like**
It would be nice to import the BigNumber class directly from the sdk.

**Describe alternatives you've considered**
Before migrating to the sdk, our code was using ethers for most things. We are currently refactoring to include the alchemy-sdk instead, but this has been the main thing we are unable to get around, apart from installing BigNumber separately, or just continuing to use the ethers methods.

**Comment by thebrianchen** [comment]
@Xirynx Thanks for the feedback. I'll have the export included in the next release. Are there any other exports that you wish to see included?

**Comment by thebrianchen** [comment]
This has been released in the `v2.4.3` release.
