### ISSUE TITLE
FR: Implementation of getContractMetadataBatch method missing in alchemy-sdk-js

### ISSUE THREAD

**Issue by Kayaba-Attribution** [alchemyplatform/alchemy-sdk-js#271]
Upon using the [getcontractmetadatabatch](https://docs.alchemy.com/reference/getcontractmetadatabatch)  method, I discovered that it is not yet implemented in the Alchemy SDK.

I was curious if this method might be located under another namespace as getContractMetadata does exist.

The inclusion of this method in the SDK would significantly enhance the efficiency of my application.

Please provide an update on the availability of this method. Thank you in advance for your response.

**Comment by thebrianchen** [comment]
This is part of the `v2.5.0` release.
