### ISSUE TITLE
missing `title` field in `ContractForOwner`

### ISSUE THREAD

**Issue by taeguk** [alchemyplatform/alchemy-sdk-js#278]
### [REQUIRED] Environment

- Alchemy SDK version: 2.6.0

### [REQUIRED] Describe the problem

There is the field `title` in json of response. But there is no `title` field inside of `ContractForOwner` in SDK.

![image](https://user-images.githubusercontent.com/9107889/223433183-db3d7326-25e1-473a-a45c-5e1dc3e48a0c.png)

**Comment by thebrianchen** [comment]
@taeguk Thanks for catching this! This will go out in the next release.
