### ISSUE TITLE
Network.ETH_SEPOLIA doesent exist

### ISSUE THREAD

**Issue by Borming** [alchemyplatform/alchemy-sdk-js#283]
### [REQUIRED] Environment

- Browser version:
- Alchemy SDK version: latest 2.6.0

### [REQUIRED] Describe the problem
The docs say use Network.ETH_SEPOLIA but its undefined

#### How to reproduce:
console.log( Network.ETH_SEPOLIA )

#### Relevant code or sample repro:
Network.ETH_SEPOLIA

**Comment by thebrianchen** [comment]
Seoplia has been added in `v2.6.1`.
