### ISSUE TITLE
Thumbnail on video files does not load

### ISSUE THREAD

**Issue by outdoteth** [alchemyplatform/alchemy-sdk-js#285]
the returned 'thumbnail' endpoint results in a 500 error: https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/1027b6aea733555630d2a9a10767f4e6

<img width="927" alt="Screenshot 2023-03-16 at 18 29 27" src="https://user-images.githubusercontent.com/37438950/225718725-e793d7e6-879d-4210-9824-05a15f18235d.png">

For the following collection: 0xcb0477d1af5b8b05795d89d59f4667b59eae9244

**Comment by thebrianchen** [comment]
@outdoteth Are you still running into these issues?

**Comment by wcjohnson11** [comment]
I am still running into these issues

**Comment by thebrianchen** [comment]
@wcjohnson11 Sorry to hear that. I've reopened the issue. Can you share a few examples of failing calls so we can investigate?
