### ISSUE TITLE
to-get-all-nfts-owned-by-an-address support for sepolia

### ISSUE THREAD

**Issue by miukki** [alchemyplatform/alchemy-sdk-js#289]
**Is your feature request related to a problem? Please describe.**
when this API will support sepolia https://docs.alchemy.com/docs/how-to-get-all-nfts-owned-by-an-address

how to contribute and add fix ?

**Comment by thebrianchen** [comment]
@miukki Adding NFT support sepolia is currently on our roadmap! I'll update this ticket once it's available.
