### ISSUE TITLE
Seems getNftsForOwner allows 45 contractAddresses instead of documented 20

### ISSUE THREAD

**Issue by hixus** [alchemyplatform/alchemy-sdk-js#290]
### [REQUIRED] Environment

- Browser version: Node.js v16.18.0
- Alchemy SDK version: 2.4.2

### [REQUIRED] Describe the problem

We found out that contractAddresses limit for getNftsForOwner seems to be 45 and not 20 that is in the docs https://docs.alchemy.com/reference/sdk-getnftsforowner#options-parameters

Unclear if your docs are wrong or there is bug in the implementation. Would prefer larger limit but if this will change then can go with 20.

#### How to reproduce:

Add over 20 but under 45 contractAddresses and api works fine. If over 45 then we get Error of "Contract address filter size of: 46 is greater than the maximum allowed of: 45!"

**Comment by niveda-krish** [comment]
Thanks for pointing this bug @hixus, the limit is actually 45 and this was an error in our docs. We will update our docs
