### ISSUE TITLE
effectiveGasPrice missing in transaction receipts for optimism chain

### ISSUE THREAD

**Issue by shaileshshivam** [alchemyplatform/alchemy-sdk-js#291]
### Environment

- Browser version: node v16.14.2
- Alchemy SDK version: 2.6.2

### Describe the problem

`alchemy.core.getTransactionReceipt()` response doesn't return `effectiveGasPrice` for transactions on optimism chain. L1 fee data is also not returned via sdk request. 

#### How to reproduce:

 - Find any address for optimism chain
 - Fetch transaction receipt for any transaction belonging to the address

#### Relevant code or sample repro:

[Composer Request](https://composer.alchemy.com?share=eJyVmE9v4jAQxb9Lzj2UDVDKDZDYVtptUdvtZVWhwRlCVMdGjilFVb.7JoFSZzwO7A3N_71nJ.4bPiKxgkxFw.giUmi32rxGw95l5yLK0a50cgc5RsOo.D1P0T4ZUAUIm2n1gAKztY2_wPt1VS2i4d_P6A3kpnKBFCvMd5VzVBQH_xJNUbokLFC2Mp8XbNKTfkU1klJvQQnkkwjTljQGWTGBLjWRtpzfaCEBCy05RySU473dUK8Y0M1McLFJ59aAwLHU4nW8u4Fi5WQFgPaMu02_QNOackACOU63_RQXcDOq2QdC6I1qvJFGmfKLqkdel6lCXQKkJHhd8rhq0dwmFD1UPVpnagGFO1kbZcpjYbMcLP4E_riuQl1LxJussNrsiMkRqCeFYmayxjJqlD0e7WE1UMe3wHnYWciIYS87lJ4c8jPriZVDfmdmTqr51vosAfj87NZnDeJM.kQnzEDVVYaeZtKimaxApY39kJWD.l86DZprjXHynhA9M1ovfXxfZvgHrS0.XEeFcT2WCwZSHFVHHLF9S4zPGZ.xrh6xqoWRSm5Vgu9_2An_rBb2M_B.2iCOU63wr89H2nPq_doasyfaU75vHuGcL_aspOLwTs5JPLJM8h8lJJ415kHyROqpcW5hQ8mHPeTYlUCoh52TF9rHQiDNXJUNmfK0IwnHMuVzeC_PLW0yu5siztD4ByiLeDmZylRKnfsiZRVu60fYb3DEQ0TGG7KFHTNUSdkRZ2qGMoIkTV17IH1tHOGlGG210PK5vLw3r3icSt1F2cIDbPk7YgDgMtoDWt1Z6lmqksftlPCnx1eV0pty1hS2vEOyo0RV112f1Kq6GFvm44JTA_5iqs39VjUaZ2Xiv5s_8Q27gu95BNm4PrhVn.ZJlir7ONFSIh1YVib__uHaEjgglFF.yQXse811ZsWNlgma_yXbNiu7.vKTfC7LuzuSDalZp441lvc0ctY269Tx5q1Zt_rSBtfa2Mc15A7sFF12i4t4LmSGyvqbAiN63mIFMbXUtc_Xi2gNBvLnCq._dYgu3zu962uEAVwP_n3oiH7SjXviCuJFp9uNRRJ3flzFMBiUxX4PfoguJJe9ZLEcwDLGXmd5Fb18.gO.2xkH)

https://github.com/shaileshshivam/optimism-test

**Comment by shaileshshivam** [comment]
@thebrianchen I wanted to know whether this is a valid bug or if there is a mistake on my end. I would greatly appreciate it if you or someone from your team could investigate this matter and provide any necessary guidance or clarification.

**Comment by thebrianchen** [comment]
@shaileshshivam The alchemy sdk uses ethers.js to execute and format transaction receipts, and it only populates the `TransactionReceipt` with fields that all evm chains have and strips unrelated fields. As a workaround, you can call `alchemy.core.send()` and send the request as raw json-rpc call. That way, all the fields you want will be returned in the response.

**Comment by shaileshshivam** [comment]
@thebrianchen Thank you for your help! I was able to get the L1 details through the RPC call, but unfortunately, I'm still stuck on trying to get the L2 gas price. Do you happen to have any ideas or suggestions that might help me out ?

**Comment by thebrianchen** [comment]
@shaileshshivam Can you share a sample call you are trying to make?

**Comment by shaileshshivam** [comment]
```
const alchemy = new Alchemy({
    apiKey: process.env.ALCHEMY_API_KEY,
    network: Network.OPT_MAINNET,
})

const transactionHash = "0x852b87d82317aa35cbe737ebc128587929f65d41a15517218d3e96fcb5ab23c8"

async function getTransactionReceipt(hash) {
    const receipt = await alchemy.core.send("eth_getTransactionReceipt", [hash])
    const gasUsed = receipt.gasUsed
    const effectiveGasPrice = receipt.effectiveGasPrice

    console.log(receipt)

    console.log({
        gasUsed,
        effectiveGasPrice
    })

}


await getTransactionReceipt(transactionHash);
```

**Comment by shaileshshivam** [comment]
@thebrianchen have attached the sample call

**Comment by thebrianchen** [comment]
@shaileshshivam `effectiveGasPrice` is supported only on eip-1559 transactions, which is only available on bedrock. We'll have to wait until the [mainnet upgrade](https://oplabs.notion.site/Bedrock-Mission-Control-EXTERNAL-fca344b1f799447cb1bcf3aae62157c5) is completed.

**Comment by shaileshshivam** [comment]
@thebrianchen thank you for your help.
