### ISSUE TITLE
400: Page key is not found or expired, please try again with a valid page key

### ISSUE THREAD

**Issue by taeguk** [alchemyplatform/alchemy-sdk-js#292]
### [REQUIRED] Environment

- Alchemy SDK version: 2.6.1

### [REQUIRED] Describe the problem

> ```400: Page key is not found or expired, please try again with a valid page key```

This error sometimes happens when using `getNftsForOwner`.
How to avoid this error?

**Comment by thebrianchen** [comment]
@taeguk How often are you running into this error? Our page keys are typically valid for 15 minutes before they expire. If you are running into this during normal pagination without delays, can you share your example usage?

**Comment by taeguk** [comment]
Some users request the next page after more than 15 minutes. Not so critical, but it happens often.

**Comment by thebrianchen** [comment]
Got it. At this time, I don't think we will prioritize extending the valid time range of our page keys. Your best bet will be to reload the page or issue a new API call and paginate accordingly.

**Comment by taeguk** [comment]
@thebrianchen okay, thanks
