### ISSUE TITLE
websocket does not return subscription id

### ISSUE THREAD

**Issue by FounderCasey** [alchemyplatform/alchemy-sdk-js#295]
### [REQUIRED] Environment

- Browser version:
- Alchemy SDK version: 2.6.2

### [REQUIRED] Describe the problem
Using the websocket `.on` method, does not return subscription id

#### How to reproduce:
```
alchemy.ws.on(
      {
        method: AlchemySubscription.MINED_TRANSACTIONS,
        addresses: [
          {
            from: address,
          },
          {
            to: address,
          },
        ],
        includeRemoved: false,
      },
```

**Comment by FounderCasey** [comment]
@nickgonzales04

**Comment by thebrianchen** [comment]
@FounderCasey The SDK abstracts away the concept of a subscription id. To unsubscribe, you can call `off()` or `removeAllListeners()`.

**Comment by FounderCasey** [comment]
Hey @thebrianchen, thanks for the reply.

We have quite a few websocket connections active at a time, so we'd like to be able to close only one. The current way is via a for loop of connected and verified contracts. We don't need to use the SDK but we'd like to

**Comment by thebrianchen** [comment]
@FounderCasey Just double checking, are you holding multiple websocket connections subscribed to the same events with the same listeners?

**Comment by FounderCasey** [comment]
Hey Brian, yes, we were. We can close this now, as we've gone about this differently.

cc / @NickGonzalez04

**Comment by thebrianchen** [comment]
@FounderCasey Ah got it. What was your use case // what solution did you end up using? Thanks!
