### ISSUE TITLE
Incompatible with moduleResolution: bundler

### ISSUE THREAD

**Issue by florrdv** [alchemyplatform/alchemy-sdk-js#302]
### [REQUIRED] Environment

- Browser version: N/A
- Alchemy SDK version: 2.7.0

### [REQUIRED] Describe the problem
The alchemy-sdk package seems to be incompatible with the new `"moduleResolution": "bundler"` option introduced in TypeScript 5.0, this can be resolved by adding `"types": "./dist/src/index.d.ts"` to the `"exports"` section in `package.json`.

#### How to reproduce:
This issue can be reproduced by importing the alchemy-sdk package (latest version) in a TypeScript project with `moduleResolution` set to `bundler`.

**Comment by florrdv** [comment]
Hi @thebrianchen! Thank you so much for the swift response. 

It looks like you need to enable the strict compiler options for it to show up. I've put up a repro example [here](https://github.com/florrdv/alchemy-declarations-missing-repro), which can be ran using the start script. I believe it is important to use `tsc` as well.

**Comment by thebrianchen** [comment]
@florrdv Thanks for the repro example! Was able to see the error and how your PR fixes it.

**Comment by thebrianchen** [comment]
Closing the issue since the fix has been merged. Will release in the `v2.8.1` early next week.
