### ISSUE TITLE
FR: Oauth option instead of API key

### ISSUE THREAD

**Issue by mvanmeerbeck** [alchemyplatform/alchemy-sdk-js#309]
**Is your feature request related to a problem? Please describe.**
I would like to use alchemy node directly from a frontend without exposing an API key. Using an access token for the auth could resolve this problem.

**Describe the solution you'd like**
Implementing Oauth on the alchemy node & provide a way to configure it in the sdk.
The admin would configure the oauth in his alchemy dashboard. The user would login using an openid flow, then the access token would be pass to every call to the node and be authorized

**Describe alternatives you've considered**
I consider using the alchemy on the backend but that means a lot of useless relay between front and back. 
Also considered using a proxy in front of the alchemy node but then the sdk can't be use anymore (still need to pass the api key)

**Comment by thebrianchen** [comment]
@mvanmeerbeck This is something we are currently considering on our roadmap.
