### ISSUE TITLE
`getTokensForOwner` throwing `Invalid params` exception

### ISSUE THREAD

**Issue by mholtzman** [alchemyplatform/alchemy-sdk-js#323]
### [REQUIRED] Environment

- Browser version:
- Alchemy SDK version: 2.8.3

### [REQUIRED] Describe the problem
Making the same request as is described in #319. It seems to have been changed from 2.8.2 to 2.8.3 but now the exception is different:

```
Error: Invalid params: expected a valid token contract address.
    at /node_modules/alchemy-sdk/dist/cjs/alchemy-provider-6f540e4a.js:88:39
    at Array.forEach (<anonymous>)
    at /node_modules/alchemy-sdk/dist/cjs/alchemy-provider-6f540e4a.js:85:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: -32602,
  data: undefined
}
``` 

#### How to reproduce:
Using the same script in #319. Note that no "token contract address" is even provided to this API call.

**Comment by thebrianchen** [comment]
@mholtzman ah my bad on this one. I got caught up on the `0x` issue with token balances. I've repro'd this one and it should be a straightforward fix.

**Comment by thebrianchen** [comment]
@mholtzman The underlying issue in the backend has been fixed as well, so you should be able to make the call now without errors.
