### ISSUE TITLE
FR: <add websocket disconnected & reconnected hook>

### ISSUE THREAD

**Issue by WangZiHao752** [alchemyplatform/alchemy-sdk-js#329]
**Is your feature request related to a problem? Please describe.**
I want to add a function to websocket that will trigger when the connection is disconnected or reconnected.  use for inform my telegram bot.  Thank you very much if you can add it

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thebrianchen** [comment]
@WangZiHao752  You can access the websocket directly on the provider and add the event listener.

```ts
const p = await alchemy.config.getWebSocketProvider();
p._websocket.addEventListener('open', console.log('opened'));
p._websocket.addEventListener('close', console.log('closed));
```

Marking the issue as closed since we already the functionality, but feel free to ask any follow up questions you may have
