### ISSUE TITLE
GetOwnersForContractResponse missing  return type

### ISSUE THREAD

**Issue by jnastaskin** [alchemyplatform/alchemy-sdk-js#341]
### [REQUIRED] Environment
Typescript
- Browser version: Chrome Version 114.0.5735.106 
- Alchemy SDK version: 2.9

### [REQUIRED] Describe the problem
For the method `getOwnersForContract`, the return type `GetOwnersForContractResponse`  is missing a return type, `pageKey`.  It's currently only present on `GetOwnersForContractWithTokenBalancesResponse`, i.e. you have to provide options when calling the `getOwnersForContract` method.  This creates false errors when using this function in Typescript since Typescript doesn't know that pageKey actually is in fact returned.
#### How to reproduce:
See below

#### Relevant code or sample repro:

In typescript, the `resp`  var below does not contain pageKey
```
  const resp = await alchemy.nft.getOwnersForContract(
      "0x2953399124f0cbb46d2cbacd8a89cf0599974963"
  );
  console.log("resp = ", resp);
```

However, in typescript, the `resp`  var below DOES contain pageKey

```
const resp = await alchemy.nft.getOwnersForContract(
            "0x2953399124f0cbb46d2cbacd8a89cf0599974963",
            { withTokenBalances: true }
        );
        console.log("resp = ", resp);
```

**Comment by thebrianchen** [comment]
@jnastaskin Sorry for the delay in responding to this! Should be fixed in the next version. Thanks for catching this :)
