### ISSUE TITLE
Send private transaction, quick mode is invalid

### ISSUE THREAD

**Issue by ijulymoon** [alchemyplatform/alchemy-sdk-js#351]
### [REQUIRED] Describe the problem
Send private transaction, fast mode is invalid.
It is invalid to use the fast mode for buying coins or transferring money. The query shows that the fast mode is false, and it is still the normal mode. Replacing null with a block number is the same. Add hash at the end of the query link: https://protect.flashbots.net/tx/

#### Relevant code or sample repro:

`import { Network, Alchemy, Wallet, Utils } from "alchemy-sdk";
import dotenv from "dotenv";
dotenv.config("../.env");
const { API_KEY, PRIVATE_KEY } = process.env;
const settings = {
  apiKey: API_KEY,
  network: Network.ETH_MAINNET,
};

const alchemy = new Alchemy(settings);
const wallet = new Wallet(PRIVATE_KEY);

const transaction = {
  to: "0xA87258c0FF0D06769d3471fbd73939dFCbcFdC86",
  value: Utils.parseEther("0.001"),
  gasLimit: "21000",
  maxPriorityFeePerGas: Utils.parseUnits("5", "gwei"),
  maxFeePerGas: Utils.parseUnits("20", "gwei"),
  nonce: await alchemy.core.getTransactionCount(wallet.getAddress()),
  type: 2,
  chainId: 1,
};

const rawTransaction = await wallet.signTransaction(transaction);
const result2 = await alchemy.transact.sendPrivateTransaction(
  rawTransaction,
  null,
  { fast: true }
);`

**Comment by thebrianchen** [comment]
@ijulymoon Sorry for not responding to this issue earlier! Is this an issue with what the SDK is sending over in the params?
