### ISSUE TITLE
Filters for websocket sdk not working properly with on pending transaction event

### ISSUE THREAD

**Issue by WanderningMaster** [alchemyplatform/alchemy-sdk-js#352]
### [REQUIRED] Environment

- Nodejs version: v18.16.0
- Alchemy SDK version: 2.9.2

### [REQUIRED] Describe the problem
I'm trying to subscribe for `alchemy_pendingTransactions` event with alchemy websocket sdk to listen for specific wallet addresses and it's working just fine if i set one of them either `toAddress` or `fromAddress` parameter, but if I set both it will listen only for transactions which includes `toAddress`
#### How to reproduce:
* Run code snippet provided below
* Make sure that you will see `Pending tx log` for transaction where `toAddress` includes in `addresses` array but not for `fromAddress`
#### Relevant code or sample repro:
```js
const addresses = [...]

const fromWalletAddreses = addresses.map((x) => ({
    from: x
  }))
const toWalletAddreses = addresses.map((x) => ({
    to: x
}))

alchemy.ws.on({
    method: AlchemySubscription.MINED_TRANSACTIONS,
    addresses: [
        ...fromWalletAddreses,
        ...toWalletAddreses
    ]
}, (tx) => console.log('Mined tx: ', tx.transaction.hash))

alchemy.ws.on({
    method: AlchemySubscription.PENDING_TRANSACTIONS,
    toAddress: addresses,
    fromAddress: addresses,
}, (tx) => console.log('Pending tx: ', tx.hash))
```

**Comment by henrytirla** [comment]
HI, my approach in python may help. I actually got inspired by the documentation 
`import asyncio
import json
import websockets
from web3 import Web3
import requests
from websockets import connect


from alchemy import Alchemy, Network
"""
for reference Subscription Type	Description
alchemy_minedTransactions	Emits full transaction objects or hashes that are mined on the network based on provided filters and block tags.
alchemy_pendingTransactions	Emits full transaction objects or hashes that are sent to the network, marked as "pending", based on provided filters.
newPendingTransactions	Emits transaction hashes that are sent to the network and marked as "pending".
newHeads	Emits new blocks that are added to the blockchain.
logs	Emits logs attached to a new block that match certain topic filters.

"""

api_key = "Enter your Alcheny API KEY HERE"
network = Network.ETH_MAINNET


url = f"https://eth-mainnet.g.alchemy.com/v2/{api_key}"
alchemy_ws_url="wss://eth-mainnet.g.alchemy.com/v2/WoUWFd2SYi7sNbmTTaT_fWMPCOUZ8yDI"
alchemy= Alchemy(api_key,network)
async def subscribe_to_pending_transactions():
    ws_url = alchemy_ws_url
    subscription_data = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "eth_subscribe",
        "params": ["alchemy_pendingTransactions", {
            "fromAddress":"0xbd2C6a28a156377bD75C363aD8f849c68922b4Dc" #The address you want to monitor be it from or to
            # "toAddress": "0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD"
        }]
    }

    async with websockets.connect(ws_url) as websocket:
        await websocket.send(json.dumps(subscription_data))

        while True:
            response = await websocket.recv()
            response_data = json.loads(response)
            if "params" in response_data and "result" in response_data["params"]:
                #transaction_data = response_data["params"]['result']['from']
                transaction_data = response_data["params"]
                print(transaction_data)


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(subscribe_to_pending_transactions())`

**Comment by henrytirla** [comment]
Hi, I implemented this in python and it works fine. I got inspired by the documentation. Mined and pending transactions implemented in this repo https://github.com/henrytirla/DEX-Essential-Trading-Scripts/tree/master/SDK


<img width="662" alt="Screenshot 2023-08-17 at 21 40 16" src="https://github.com/alchemyplatform/alchemy-sdk-js/assets/18648533/9b787f69-8c0f-4188-bdb3-3eb7fd944273">
