### ISSUE TITLE
searchContractMetadata results very inconsistent / unreliable

### ISSUE THREAD

**Issue by bjfresh** [alchemyplatform/alchemy-sdk-js#363]
### [REQUIRED] Environment

- Browser version: Chrome 116.0.5845.96 (Arm64)
- Alchemy SDK version: 2.10.0

### [REQUIRED] Describe the problem

Results for **searchContractMetadata** are wildly inconsistent for queries of different length.

**Phrase**: 'dead'
Results: 20+, including DeadFellaz, DeadFrenz, DeadFrenz Pass

**Phrase**: 'deadf' (should return DeadFellaz, DeadFrenz, DeadFrenz Pass)
Results: 0

**Phrase**: 'degen'
Results: 20+, including Degenz

**Phrase**: 'degenz'
Results: 0

[Here's a Loom](https://www.loom.com/share/2a3699f157a9431cae0c91135982cc03)

#### How to reproduce:

[This behaviour is present on the v3 reference page](https://docs.alchemy.com/reference/searchcontractmetadata-v3)

#### Relevant code or sample repro:

```ts
import { NftContract } from 'alchemy-sdk'

import { alchemyService } from '@/services'

export async function alchemySearchContractMetadata({
  searchQuery,
  chainId
}: {
  searchQuery: string
  chainId?: number
}): Promise<{ contractMetadata: NftContract[] }> {
  
  try {
      const contractMetadata: NftContract[] = await alchemyService({chainId}).nft.searchContractMetadata(searchQuery)
    return {
      contractMetadata
    }
  } catch (error) {
    console.error(error)
  }
  
  return {
    contractMetadata: [] as NftContract[]
  }
}

```

**Comment by thebrianchen** [comment]
@bjfresh thanks for filing an issue! We're aware of this inconsistent search performance. It's on the backlog, but not currently prioritized. I'll keep this issue open and update it when we do work on it.

**Comment by bjfresh** [comment]
Not stale

**Comment by bjfresh** [comment]
Not stale

**Comment by bjfresh** [comment]
Not stale

**Comment by bjfresh** [comment]
Not stale

**Comment by bjfresh** [comment]
Not stale
