### ISSUE TITLE
Issue when fetching NFTs

### ISSUE THREAD

**Issue by outdoteth** [alchemyplatform/alchemy-sdk-js#374]
When trying to make the following request I get a 500 error with "Error fetching nft data":

```
https://eth-mainnet.g.alchemy.com/nft/v2/mVmtWXBYrlQuutKPNMSy43i6vLhTSDdc/getNFTs?contractAddresses[]=0x9fa4ef95e229790ce1452a49ccede42650376b4b&owner=0xc452da068b2ee2d40c3643abb801b34404f6093d&pageSize=50&withMetadata=true
```

Why does this give me an error? It fetches fine on opensea: https://opensea.io/collection/shroomieznfts

**Comment by thebrianchen** [comment]
@outdoteth Thanks for filing the issue! We had a period of degraded service today, but the issue has been resolved now and we're back to normal. I'm going to close the issue but feel free to ask any other questions you can have
