### ISSUE TITLE
Confusing Type Returned for interface NftMetadata

### ISSUE THREAD

**Issue by jnastaskin** [alchemyplatform/alchemy-sdk-js#375]
### [REQUIRED] Environment

- Browser version: chrome Version 116.0.5845.187 (Official Build) (x86_64)
- Alchemy SDK version: 2.10.1

### [REQUIRED] Describe the problem

The interface NftMetadata is currently defined as 
```
export interface NftMetadata extends Record<string, any> {
    /** Name of the NFT asset. */
    name?: string;
    /** A human-readable description of the NFT asset. */
    description?: string;
    /** URL to the NFT asset image. */
    image?: string;
    /**
     * The image URL that appears along the top of the NFT asset page. This tends
     * to be the highest resolution image.
     */
    external_url?: string;
    /** Background color of the NFT item. Usually defined as a 6 character hex string. */
    background_color?: string;
    /** The traits, attributes, and characteristics for the NFT asset. */
    attributes?: Array<Record<string, any>>;
}
```
However the actual return response seems to use `traits` instead of `attributes`.   I understand the interface  is able to get away with this via  `extends Record<string, any>` but it would be great for typescript developers if this type got updated to reflect something closer to the actual return response.

#### How to reproduce:

```
const ownedNfts = await alchemy.nft.getNftsForOwner(
            ownerAddress,
           {contractAddresses: contractAddresses}
        );
console.log('ownedNfts = ', ownedNfts)
```

#### Relevant code or sample repro:
```
export interface NftMetadata extends Record<string, any> {
    /** Name of the NFT asset. */
    name?: string;
    /** A human-readable description of the NFT asset. */
    description?: string;
    /** URL to the NFT asset image. */
    image?: string;
    /**
     * The image URL that appears along the top of the NFT asset page. This tends
     * to be the highest resolution image.
     */
    external_url?: string;
    /** Background color of the NFT item. Usually defined as a 6 character hex string. */
    background_color?: string;
    /** The traits, attributes, and characteristics for the NFT asset. */
    attributes?: Array<Record<string, any>>;
}
```

**Comment by jnastaskin** [comment]
Not sure if this is more qualified as a feature request or bug but I'll let the alchemy team decide! :)

**Comment by thebrianchen** [comment]
@jnastaskin Thanks for filing this issue and apologies for the delayed response! We've left it as-is mainly because some NFTs will use `traits` while others use `attributes`, with `attributes` being more prevalent. I'm going to mark this issue as closed, but feel free to ask any other questions you may have!
