### ISSUE TITLE
getAssetTransfers returns transfers that never happened

### ISSUE THREAD

**Issue by wojciech-turek** [alchemyplatform/alchemy-sdk-js#376]
### Environment

- Browser version: N/A
- Alchemy SDK version: 2.10

### Describe the problem

When using the `getAssetTransfers` from the `core` module, it returns transfers from failed transactions.
This is extremely confusing and messes up balance calculations based on the transfers data.

I am using Alchemy for accounting purposes and deal with large number of wallets and transactions.
If I were to `getTransactionReceipt` for each transfer to see if the status is `1` or `0` that would blow up my CCU usage.

#### How to reproduce:

Composer result example:

https://composer.alchemy.com?share=eJyVmMty4jgUht.F6ywg92YHTJh01UxCJeleTNcUJeRjcEWWPJLcwHTl3Ue2gehyJJhNQp3z.b91OZJl.crompQ8G2Wg19lFVpl.In_udSm4ykY.fmU.CWvA5Amja6h2ixXosVKg3yThqgCpjIqRJbAk83GBOr2Jd_BjxsSGcAq4k8eknCaEtUykSS6S8vkTNMmJJgmfIxLzabtOaDuOL0ChrHWsVQiIeUr4pwGl52RXEaVBjnn_G97EGIm5qrJqGNHQTdd0TfgKHT0US.k9bIE2bZ8SZp_M7URFVTcaXogs9c5Su3FbkcOyWS20JBQmTND3ye6RqLaYD9IIkPZ4aqolyKTLHon4TAljuLzLRFRWOeBiG7A9zMJdEEpFw51Kc8I_v2z7EXTUz.gq6nbsGAq4dmf5mvvoPhrQouRLouxNwAn7vKnwsjJV9Dvxu2tnYqpvCuRzDZK04xi3CDDfrwB4LJUW0i5VL_FrVkTNZelsd0444EHvdy1f8ZnANOhaQJJxLVoaQTqmR.Y9NB3TW5U_bes32ZcIfL53sq9RHPGfihyZqC6K0LOSmS063HnRdFT.h1hFxV0OUeKaGD2XQhQh3ocR.kUIjU.XMYOoXs2CISsY61D2mUJ01vxMdt2MtU8wL76vPIdtaHaCP_sJfQX8n2d4ilNPwYcvRNI_Xb0mbXoi7bJfrEmfA3OWk9qPyTmORxZx.sYpg7PmPEqecD01zwk25rzfQ45NiZgG2Dl_sX0sBmKe9lsvVocYdMorWkUo5butzSMM4W_ux7DPV2RrXqiiPS.OAOYgw.c8igQ_JS.5ylf2QZ.lsOkGt996PY2XRLQxWVwxB56bhliLJuYRJX3XOgD9YcOIwEUKLahg383nn3uYxbK_WpknvJANfhqOAJhH2uCU2ilLRO.mA4dyFYjaUMA1dS2khvyBa7mbmwNvcGZCkcBnx2lYqIeoTzemfpU253a0Xvysre5OM6YdZuCQD2UsG1GrmZDPG_48HE17_hkTQvpHaDfuKZ5mb3hT7USoeSXMOZTZ0ZAOSZQyvZoKxsAvSjTt6bvhSDlgQMyju8eIyPucp3ytSXWcHFfopmxdqR4Fy806KdA2o2lXb3s7SidhazjoBTNfX_Bt3G7cV9RgTtreacmN_4qfwd5mR21agnmi_apE_hGkXF277tuOOopj0GYVEEnXiaUZARyPpqrMDcu.YEpxrLUsl_bOxZ7rCGB7dNcU.Q2CJbSjIe3dKVjBkC38DcsJh7wpzwBuYyEpY28cNI3ooWakP11F3p5pLuaYbFRAhC7mb1Rv52zlBpZXC8pK4Dp8hSPJQKvW5MqXdLGPvy.adbIR8j0bDQ53zk_kOnXNXBNJqu.tM.qradhS1uTwF0jRRbORlg1cZNScBlftzcvoh2FMUXDSFpd5aR5_gqSXg.7.3eWw.zEc3tyYX6oGWhLGC52ZdhZSVP23xygbDu9vBzd3XwykBRJs2XGeS1CmedlgO7y8vX6YXJP86orC7Pb2bjoo4HJ8fz28GSxvyZf7YnZNSXFnBuTjP_DXbYs-

Sample response of a invalid transfer:

```json
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "transfers": [
      {
        "blockNum": "0xb4fa63",
        "uniqueId": "0xb9d2fc549e28a2d28fcfdd10d2c6df2a7702104b1dccadb7e0d26aee909ba976:external",
        "hash": "0xb9d2fc549e28a2d28fcfdd10d2c6df2a7702104b1dccadb7e0d26aee909ba976",
        "from": "0x1264eb4ad33cef667c0fe2a84150b6a98ff4caf7",
        "to": "0x7a250d5630b4cf539739df2c5dacb4c659f2488d",
        "value": 7.858275973456758,
        "erc721TokenId": null,
        "erc1155Metadata": null,
        "tokenId": null,
        "asset": "ETH",
        "category": "external",
        "rawContract": {
          "value": "0x6d0e345ce8e0844c",
          "address": null,
          "decimal": "0x12"
        }
      }
    ]
  }
}
```

Etherscan Link to the transaction:

https://etherscan.io/tx/0xb9d2fc549e28a2d28fcfdd10d2c6df2a7702104b1dccadb7e0d26aee909ba976

### Suggested solution

Alchemy should internally review the transfers data and remove any transfers that come from failed transactions.

**Comment by thebrianchen** [comment]
@wojciech-turek Thanks for filing an issue along with a repro! This is a long-standing limitation our of transfers API that we’re aware of. We’re currently working on an updated API that will include transaction receipt data and more. In the meantime, aside from using `getTransactionReceipt`, you can also use `alchemy_getTransactionsReceipts` to fetch all the receipts for a given block. I’m going to mark this issue as closed, but feel free to ask any other follow up questions you may have.
