### ISSUE TITLE
Network.ARB_SEPOLIA doesnt exist

### ISSUE THREAD

**Issue by antondalgren** [alchemyplatform/alchemy-sdk-js#387]
### [REQUIRED] Environment

- Browser version: - 
- Alchemy SDK version: 2.10.1

### [REQUIRED] Describe the problem
See #283

**Comment by thebrianchen** [comment]
@antondalgren This is on our roadmap, and we'll cut a new release when it's out! Stay tuned :)

**Comment by antondalgren** [comment]
@thebrianchen Thanks for the update. It seems to be quite urgent given the fact that we received an email saying Goerli on Arbitrum is EoL on 18th of november.

> **Goerli End-of-Life Dates:**
Arbitrum: 11/18
Ethereum: 1/1

Thanks for creating a PR @59023g

**Comment by bmoyroud** [comment]
Hey @antondalgren @59023g - appreciate the PR and raising issue!

We just shipped [v2.11.0](https://github.com/alchemyplatform/alchemy-sdk-js/releases/tag/v2.11.0) which includes support for Arb Sepolia.

Sorry for the delay in getting this out & let us know if any questions!
