### ISSUE TITLE
Invalid URL error returned for core methods in v3

### ISSUE THREAD

**Issue by sa-ma** [alchemyplatform/alchemy-sdk-js#393]
### [REQUIRED] Environment

- Node version: 20.9.0
- Alchemy SDK version: 3.0.0
- Next.js version: 14.0.3  

### [REQUIRED] Describe the problem
The `getTokensForOwner` throws a `TypeError: Invalid URL` when called

#### How to reproduce:
Create a route handler in Next.js v14 and call the `getTokensForOwner` method

#### Relevant code or sample repro:
![image](https://github.com/alchemyplatform/alchemy-sdk-js/assets/24418733/30c43fbb-1516-42e3-8b50-c3cc2a2ee2fe)

**Comment by ChiuMungZitAlexander** [comment]
Got the same error here
```
{
    "reason": "missing response",
    "code": "SERVER_ERROR",
    "requestBody": "{\"method\":\"eth_getBalance\",\"params\":[\"0xb029143abe1cb60a69a8e4670ed26949ae213bc5\",\"latest\"],\"id\":42,\"jsonrpc\":\"2.0\"}",
    "requestMethod": "POST",
    "serverError": {}
}
```
I think it's because nextjs v14 only supports `fetch`. Thus jsonRPC of alchemy-sdk will not work.

**Comment by CurtisMac** [comment]
I'm having the same issue, downgrading next to v13 also solved the issue for me

**Comment by thebrianchen** [comment]
@CurtisMac See #400 for a workaround by passing in your own ethers connection object.

**Comment by CurtisMac** [comment]
Thanks @thebrianchen, that worked!
