### ISSUE TITLE
FR: Support New Polygon Testnet Amoy

### ISSUE THREAD

**Issue by ikisuke** [alchemyplatform/alchemy-sdk-js#411]
**Is your feature request related to a problem? Please describe.**
mumbai, polygon's testnet, will be discontinued and a new amoy network will be added.

**Describe the solution you'd like**
I would like to see amoy added to Network.

**Describe alternatives you've considered**
Stopping support for Polygon testnet

**Additional context**
Detail: [Add any other context or screenshots about the feature request here.
](https://polygon.technology/blog/introducing-the-amoy-testnet-for-polygon-pos)

**Comment by thebrianchen** [comment]
@ikisuke We are working on support for Amoy and will update the SDK when it is released.

**Comment by thebrianchen** [comment]
this has been published in `v.3.2.0`
