### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'address')

### ISSUE THREAD

**Issue by eheimburg** [alchemyplatform/alchemy-sdk-js#428]
### [REQUIRED] Environment

- Browser version: not using a browser
- Alchemy SDK version: 3.3.0

### [REQUIRED] Describe the problem
The API is calling the v3 endpoints even though it expects the results in v2 format. When I get back the results of `alchemy.nft.getNftsForOwner`, I can see that the raw JSON results include v3 data (e.g. `contractAddress` instead of `contract.address`). However, the typescript types only allow for `contract.address`, there is no way to actually use the results. 

#### How to reproduce:
call `alchemy.nft.getNftsForOwner` on a wallet that has NFTs, try to view the `contract.address` variable in the results, see that it is undefined

**Comment by thebrianchen** [comment]
@eheimburg Can you share the exact code you are calling? I tried calling:
```
const response = await alchemy.nft.getNftsForOwner('vitalik'.eth);
console.log(response.ownedNfts[0].contract.address);   // prints `'0x0000000000cf80E7Cf8Fa4480907f692177f8e06'`
```

I checked all the contracts in the response and all of them were defined.
