### ISSUE TITLE
Error messages not bubbled up to caller when making API calls via the sdk

### ISSUE THREAD

**Issue by TheWisestOne** [alchemyplatform/alchemy-sdk-js#429]
### [REQUIRED] Environment

- Browser version: node.js, no browser
- Alchemy SDK version: 3.2.0, but I suspect latest as well

### [REQUIRED] Describe the problem
When making an sdk call to update webhook configuration (via `sdk.notify.updateWebhook` or `sdk.notify.createWebhook`), The error that is bubbled up to the caller has no information for the caller to know what the actual issue is.
Specifically, the `message` field on the error looks like `400: [Object object]`

#### How to reproduce:
Because I can't see the underlying error, I don't know what I'm doing in my code that is *causing* an error, but one way to reproduce is to attempt to call `sdk.notify.updateWebhook` for an address activity webhook, with a set of `newAddresses` that is >= 35k in length. In this case, we get back `Error: 503: [Object object]` consistently.

#### Relevant code or sample repro:
I have a strong suspicion I have found the place in the code where this issue stems from:
https://github.com/alchemyplatform/alchemy-sdk-js/blob/5fdff2fb76dc668cf10be3dbf8955a6d92303414/src/internal/dispatch.ts#L58
From the axios docs, the `response` object that comes back from an axios call contains a `data` field that is an object, and so the construction of the error string in this line, which is currently:
```
lastError = new Error(response.status + ': ' + response.data);
```
Is broken because the stringification of `response.data` will always be `[Object object]`

I think this line needs to look like
```
lastError = new Error(response.status + ': ' + JSON.stringify(response.data));
```
or perhaps (from the axios docs)
```
lastError = new Error(response.status + ': ' + response.data.toJSON());
```

**Comment by thebrianchen** [comment]
@TheWisestOne Thanks for posting the issue along with your detailed investigation! I tried reproducing the 503 error with the following code:
```
const addAddress = '0x7f268357A8c2552623316e2562D90e642bB538E5';
const addAddresses = new Array(36000).fill(addAddress);
try {
    await alchemy.notify.updateWebhook(addressWh, {
      addAddresses,
      removeAddresses: [removeAddress]
    });
  } catch (e: any) {
    console.log('found error', e.message);
  }
```

The resulting log prints:
```
  console.log
    found error 503: {"message":"Internal server error","name":"ServerError"}
```

The output is the same even if I use `JSON.stringify(response.data)`  on the line you mentioned. Can you share your code example?

**Comment by TheWisestOne** [comment]
Hmm, so the easiest place for me to repro was during webhook creation. The code that is executing on my deployed instance is compiled javascript, which looks like:
    ```
    try {
        const webhook = await sdk.notify.createWebhook(webhookUrl, 'ADDRESS_ACTIVITY', {
            addresses,
        });
    }
    catch (error) {
        logger_1.logger.error(error.message);
        logger_1.logger.error(`Failed to create an address activity webhook with error: ${error}`);
        return null;
    }
    ```
    here `logger_1` is a simple winston logger that writes out to console.
    
   The output here is:
 ```
   {"context":{},"level":"ERROR","logLevel":"ERROR","message":"400: [object Object]"}
{"context":{},"level":"ERROR","logLevel":"ERROR","message":"Failed to create an address activity webhook with error: Error: 400: [object Object]"}
```
 so we can see that `error.message` is the string: `400: [object Object]`
 
 I will try to create a more isolated test-case, I just have to figure out how to do that with all the appropriate environment variables in place so I can run it locally
