### ISSUE TITLE
getNFTsForOwner returns incorrect JSON results when withMetadata=false

### ISSUE THREAD

**Issue by eheimburg** [alchemyplatform/alchemy-sdk-js#433]
### [REQUIRED] Environment

- Browser version: node.js v20.12.0
- Alchemy SDK version: 3.3.1

### [REQUIRED] Describe the problem
So far as I can tell this is a bug with the `getNFTsForOwner` endpoint. If `withMetadata=false` is set, the results do not match the documented output format -- it's an entirely different, undocumented format which is not supported by the Typescript library.

#### How to reproduce:

(For privacy I've replaced our key in these URLs with ALCHEMY_KEY.)
In a browser, compare the results of 

`https://polygon-amoy.g.alchemy.com/nft/v3/ALCHEMY_KEY/getNFTsForOwner?owner=0x6c1651a5ad51755f78d2fa09a6c3a3a62bf2e867&withMetadata=true`

against 

`https://polygon-amoy.g.alchemy.com/nft/v3/ALCHEMY_KEY/getNFTsForOwner?owner=0x6c1651a5ad51755f78d2fa09a6c3a3a62bf2e867&withMetadata=false`

It's expected that `withMetadata=false` would return fewer fields, but the fields are undocumented and in the wrong format. Without metadata, the contract address is in the field `contractAddress`. When metadata is included, the contract address is returned in `contract.address` -- a nested sub-object.

This bug makes it impossible to use the typescript bindings when we don't need metadata. (The typescript bindings expect the results to be `contract.address`, not `contractAddress`.

**Comment by nirmit1509** [comment]
Adding to the same API, the orderBy is working in the opposite order as expected.
I'm getting a list with oldest tokens first.
@thebrianchen Please look into this or suggest a solution if I can reverse the order with the request.
