### ISSUE TITLE
FR: remove @ethersproject/providers as a dependency in favor of ethers 

### ISSUE THREAD

**Issue by aaronzshey** [alchemyplatform/alchemy-sdk-js#435]
Currently, this sdk depends on @ethersproject/providers@5.7.2, which was released [two years ago!](https://www.npmjs.com/package/@ethersproject/providers)  Not only is this a really long time, this package also depends on a vulnerable release of ws.  Here's the npm warning from installing alchemy-sdk right now:

```node
ws  2.1.0 - 5.2.3 || 7.0.0 - 7.5.9
Severity: high
ws affected by a DoS when handling a request with many HTTP headers - https://github.com/advisories/GHSA-3h5v-q93c-6h6q
ws affected by a DoS when handling a request with many HTTP headers - https://github.com/advisories/GHSA-3h5v-q93c-6h6q
fix available via `npm audit fix --force`
Will install @alch/alchemy-web3@0.1.18, which is a breaking change
node_modules/@ethersproject/providers/node_modules/ws
node_modules/eth-lib/node_modules/ws
  @ethersproject/providers  <=5.7.2
  Depends on vulnerable versions of ws
  node_modules/@ethersproject/providers
    alchemy-sdk  *
    Depends on vulnerable versions of @ethersproject/providers
    node_modules/alchemy-sdk
```

This offending package is currently only mentioned [5 times](https://github.com/search?q=repo%3Aalchemyplatform%2Falchemy-sdk-js+%40ethersproject%2Fproviders+NOT+path%3Adocs&type=code).  All of these uses can be replaced with `ethers`, except for two:

`CommunityResourceable`: this export is currently [commented out ](https://github.com/ethers-io/ethers.js/blob/fc66b8ad405df9e703d42a4b23bc452ec3be118f/src.ts/providers/index.ts#L96)in the ethers GitHub.  I've opened an issue with them asking why.
`Formatter`: the formatter appears to be widely used, but I was unable to find a corresponding method in `ethers` (yet).  We could either find an import a solution from ethers, or just use the code from `providers`, as exposed on [npm](https://www.npmjs.com/package/@ethersproject/providers?activeTab=code) (src.ts/formatter.ts).  

Given that the formatter code has already been modified and included in the project in the form of the [getFilter](https://github.com/alchemyplatform/alchemy-sdk-js/blob/ff5c576ddb5b23eb9f4a2b5c7a7f725dcdc9c091/src/internal/core-api.ts#L99) function, I'm leaning towards just eliminating the import of formatter from an external library.  

Thoughts?

**Comment by aaronzshey** [comment]
A quick update:
[The next minor bump of ethers will bring back CommunityResourceable](https://github.com/ethers-io/ethers.js/issues/4776).  

@ethersproject/providers uses the MIT license, giving us "Permission ... to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software".  

I'll link a PR soon

**Comment by zartosht** [comment]
Just commenting to make sure this issue is kept open.
