### ISSUE TITLE
FR: StarkNet support

### ISSUE THREAD

**Issue by hugo-levet** [alchemyplatform/alchemy-sdk-js#437]
**Is your feature request related to a problem? Please describe.**
SDK works but not support TypeScript type for StarkNet network (see screenshot)
![image](https://github.com/user-attachments/assets/23cff8f2-74ff-4259-8d3b-7e9c305ad529) 

**Describe the solution you'd like**
Can you add `"starknet-mainnet"` for `Network` type ? 

**Additional context**
I did not add a pull request with only the type change because I'm not sure about full StarkNet support in the SDK. Is it StarkNet full support in the last version ?

**Comment by hugo-levet** [comment]
For now, I use this little trick:

```typescript
const config: AlchemySettings = {
    apiKey: <YOUR_API_KEY>,
    network: 'starknet-mainnet' as Network
};
```

**Comment by thebrianchen** [comment]
@hugo-levet Since starknet is not an EVM-based chain, it won't work with the underlying ethers library. Note that there is also an `AlchemySettings.url` field to pass in a custom RPC url. 

I'll be closing this issue since we don't have plans to add starknet support into the SDK.
