### ISSUE TITLE
any updated docs(tutorials) using v2.x of sdk  (question, Documentation)

### ISSUE THREAD

**Issue by jasan-s** [alchemyplatform/alchemy-sdk-js#80]
there seems to mention breaking changes. but unclear as to what exactly the are. hoping there are updated set of tutorials simialr to https://docs.alchemy.com/alchemy/tutorials (website has older using sdk 1.x)

**Comment by deric-alchemy** [comment]
We're working on this at the moment! We'll be launching a new set of docs with the SDK v2 in the next week and steadily updating all tutorials / references over the next month.

**Comment by thebrianchen** [comment]
@jasan-s Just an update! We've updated the docs and tutorials, and you can also view a full list of the changes in the SDK's [Changelog](https://github.com/alchemyplatform/alchemy-sdk-js/releases/tag/v2.0.0). 

I'm going to mark this issue as closed, but feel free to ask any other questions you may have!
