### ISSUE TITLE
websocket filtering not working

### ISSUE THREAD

**Issue by whhsw** [alchemyplatform/alchemy-sdk-js#82]
alchemy.ws.on(
    {
      method: 'logs',
      address: "xxxxxx",
    },
    res => console.log(res)
  );

the filtering is not functioning, all kinds of tx coming out

**Comment by thebrianchen** [comment]
@whhsw The `method` function currently only supports alchemy's `alchemy_pendingTransactions` filter (https://github.com/alchemyplatform/alchemy-sdk-js/blob/main/docs-md/modules.md#alchemypendingtransactionseventfilter). To get the logs, please use the `alchemy.ws.on({filter})` [syntax](https://docs.ethers.io/v5/concepts/events/#events) that matches ethers. 

So in your case:
```js
alchemy.ws.on({
  address: "xxxxx"
}, console.log);
```

Thanks for letting us know. We'll look into making the documentation better or possibly throw an error with passing in a non-alchemy subscription API into the `method` field.

**Comment by thebrianchen** [comment]
Marking the issue as closed since this is WAI, but feel free to ask any other questions you may have!
