### ISSUE TITLE
How do I instantiate a Contract object using alchemy-sdk just like with ethers.js?

### ISSUE THREAD

**Issue by thatguyintech** [alchemyplatform/alchemy-sdk-js#84]
None of these seem to work:

* `const baycContract = new alchemy.Contract(baycAddress, baycABI, provider);`
* `const baycContract = new alchemy.core.Contract(baycAddress, baycABI, provider);`
* `const baycContract = new alchemy.ethers.Contract(baycAddress, baycABI, provider);`

I get

```bash
TypeError: alchemy.Contract is not a constructor
```
or
```bash
TypeError: Cannot read properties of undefined (reading 'Contract')
```

I can’t find the `Contract` constructor in any of the namespaces 🤔 

the documentation says:

```
If you are already using Ethers.js, you should be simply able to replace the Ethers.js object with alchemy.core and it should just work.
```

[Ethers.js documentation](https://docs.ethers.io/v5/api/contract/contract/) has this API:

```javascript
new ethers.Contract( _address_ , _abi_ , _signerOrProvider_ )
```

so I’d expect this to work:

```javascript
const ethers = alchemy.core;
const baycContract = new ethers.Contract(baycAddress, baycABI, provider);
```

but I get this error:

```bash
file:///Users/thatguyintech/Documents/co/Alchemy-Hacker-Handbook/evm_snippets/LoadContract/load-contract.js:20
const baycContract = new ethers.Contract(baycAddress, baycABI, provider);
                     ^

TypeError: ethers.Contract is not a constructor
    at file:///Users/thatguyintech/Documents/co/Alchemy-Hacker-Handbook/evm_snippets/LoadContract/load-contract.js:20:22
```

Any tips?

**Comment by deric-alchemy** [comment]
Renamed the documentation to specify that you can simply replace the "Ethers.js Provider" object with Alchemy to have 1:1 functionality, not all of Ethers.js!

**Comment by thatguyintech** [comment]
for anyone who's curious about the workaround for the original problem, here's how I solved it with ethers.js and alchemy-sdk

https://github.com/alchemyplatform/Alchemy-Hacker-Handbook/blob/main/evm_snippets/LoadContract/load-contract.js
