### ISSUE TITLE
getNftsForOwner media flag for image vs video

### ISSUE THREAD

**Issue by lsbyerley** [alchemyplatform/alchemy-sdk-js#95]
Would it be possible to add a flag in the media array from the `getNftsForOwner` response to distinguish if the media is an image or video? The `gateway` variable could either be an image, which you would set the `src` of an image tag as this variable or a video. If it is a short mp4 instead of an image (so a video html tag), there is no way to tell.

**Comment by thebrianchen** [comment]
@lsbyerley Thanks for filing an issue! This field is actually already present in the `media` field of the response as `format`. See the [documentation](https://github.com/alchemyplatform/alchemy-sdk-js/blob/main/docs-md/interfaces/Media.md#format). We will have our hosted documentation updated in a bit.

I'll mark this issue as closed, but feel free to ask any questions you may have!

**Comment by lsbyerley** [comment]
@thebrianchen sure no problem! The main reason I posted this question/issue is because I do not see the format variable returned in the media object array. Am i missing something?

`"alchemy-sdk": "2.0.2",`

```js
const alchemySettings = {
  apiKey: process.env.NEXT_PUBLIC_ALCHEMY_ID,
  network: Network.ETH_MAINNET, 
};

const alchemy = new Alchemy(alchemySettings);

const data = await alchemy.nft.getNftsForOwner(ownerAddress);
```
<img width="226" alt="Screen Shot 2022-08-17 at 11 49 04 PM" src="https://user-images.githubusercontent.com/3066258/185289225-fdc860d7-55be-4a42-b3d1-906079cc2f8c.png">

**Comment by thebrianchen** [comment]
@lsbyerley yep, that's the field! Some NFTs should have the `format` field included in the payload, and we're currently working on a fix to increase the % coverage of that field, which should be reflected in the responses soon!
